/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'MarkPerry' at '27/09/13 11:43 PM' with Gradle 1.8
 *
 * @author MarkPerry, @date 27/09/13 11:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
